---

- name: Get version
  include_vars:
    file: "{{directory_latest }}/package.json"
    var: peertube_package

- pause:
    seconds: 10
    prompt: |
      Peertube is Up and ready to serve ! (￣^￣)ゞ

      Now you can set your Reverse Proxy, and go to {{ app_domain }}

  tags: info
  
- pause:
    seconds: 10
    prompt: |
      Peertube {{ peertube_package.version }} is Up and ready to serve ! (￣^￣)ゞ

      Now you can set your Reverse Proxy, and go to {{ app_domain }}

  tags: info
  #- pause:
  #    seconds: 10
  #    prompt: |2
  #        Peertube is almost ready to run!
  #        Please REVIEW the main config file and complete it accordingly.
  #        
  #        When ready, use the following command to start it and control journalctl output:
  #        $ sudo systemctl start peertube
  #        $ sudo journalctl -feu peertube
  #
  #        Once the testing period is over and all is well, consider lowering log level to warning.
  #  tags: info
  #  
