---

- name: debug app_domain
  debug:
    var: app_domain

- name: ask domain if not defined
  pause:
    prompt: Full qualified domain name for you Peertube instance? (cannot be changed once Peertube is started, so choose carefully).
  register: entry
  when: app_domain is none

- name: set app_domain
  set_fact:
    app_domain: entry.user_input
  when: app_domain is none

- import_tasks: install-nodejs.yml
  tags: install_nodejs

- import_tasks: install-peertube.yml
  tags: install_peertube

- name: Pause
  pause:
    prompt: Pause, Everything Ok ?

- import_tasks: config.yml
  tags: config
- import_tasks: upgrade.yml
  tags: 
    - never
    - upgrade

